### ISSUE TITLE
Update readme for better system service startup

### ISSUE THREAD

**Issue by skynet01** [klamann/raspi-poe-mon#2]
The current system service file won't start up for me. This fixed it for me:

i belive the issue was having the user=pi but also in your version you didn't have the run at the end. This is on the Debian 12 Bookworm release.

```
[Unit]
Description=Raspi PoE HAT Monitor
After=network.target

[Service]
Type=simple
Environment=systemd=true
ExecStart=/usr/bin/python3 /home/pi/.local/bin/raspi-poe-mon run
WorkingDirectory=/home/pi/.local/bin
User=pi
Group=pi
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
```

**Comment by klamann** [comment]
You're right, I didn't test this properly. I updated the readme to this

```
[Unit]
Description=Raspi PoE HAT Monitor
After=network.target

[Service]
ExecStart=/home/raspi/.local/bin/raspi-poe-mon run --fan-off-temp 50 --fan-on-temp 60
User=raspi
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
```

I omitted some of other entries, since they didn't seem necessary to me

* `Type=simple` is the default type
* the `Environment` section seems pointless, I just copied it from somehwere else and didn't think about it
* `WorkingDirectory` we don't really need, since we're not accessing any files relative to the executable
* `Group` was not required to make it work for me, specifying a user seems to be sufficient

**Comment by skynet01** [comment]
Yep yours works as well!
