### ISSUE TITLE
Waveshare E-Ink HAT

### ISSUE THREAD

**Issue by SlimeV2** [klamann/raspi-poe-mon#6]
Hello,
first of all thank you very much for this, I have been using it with my PoE HAT B for a long time and it has been working perfectly.

But now I have a question:
I want to swap to an Waveshare E-Ink HAT. Do you know if it will also work with one of these?

Thank you in advance!

**Comment by klamann** [comment]
Hi, I built this tool specifically for the OLED display of the PoE HAT, since this is the only display I have at hand to test with. It might work with other displays that are connected through I2C, but the status panel has been designed for the 128x32 pixel monochrome display of the PoE HAT and will not scale to other resolutions. So if it connects, and your E-Ink display has a higher resolution, all information will be crammed in a corner and probably too small to read.

I'm not planning support for other displays, but feel free to fork this project and adapt it to your new display. Good luck! :)
